-- Add migration script here
CREATE TABLE SIGNED (
    USER_ID TEXT NOT NULL,
    USER_TAG TEXT NOT NULL,
    USER_NAME TEXT NOT NULL,
    KSM_ADDRESS TEXT NOT NULL,
    MOVR_ADDRESS TEXT NOT NULL,
    ROLES TEXT,
    AVATAR TEXT,
    CREATE_DATE TIMESTAMP NOT NULL,
    PRIMARY KEY (USER_ID)
)
