-- Add migration script here
CREATE TABLE users (
    USER_ID TEXT NOT NULL,
    USER_NAME TEXT NOT NULL,
    ADDRESS_TYPE TEXT NOT NULL,
    ADDRESS TEXT NOT NULL,
    ROLES TEXT,
    AVATAR TEXT,
    CREATE_DATE TIMESTAMP NOT NULL,
    UPDATE_DATE TIMESTAMP NOT NULL,
    PRIMARY KEY (USER_ID, ADDRESS_TYPE)
)
